### ISSUE TITLE
edoc_opts (rebar.config)

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [vkatsuba/rebar3_plugin#11]
```
{edoc_opts, [
    {includes, ["src"]},
    {preprocess, true}
]}.
```

The last option is especially interesting when macros (@elbrujohalcon's favourite Erlang component) are present. The `includes` I'd have to check (can't remember of the top of my head) but I know it was important for us at a point in time.

**Comment by vkatsuba** [comment]
Good point. Thanks.
