### ISSUE TITLE
erl_opts (rebar.config)

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [vkatsuba/rebar3_plugin#12]
I'm used to having this as simple as

```
{erl_opts, [
    debug_info,
    warn_export_vars,
    warn_missing_spec_all,
    warn_unused_import,
    warnings_as_errors,
    {i, "src"}
]}.
```

because most other options are already there, by default, but one would've to parse the existing list.

**Comment by elbrujohalcon** [comment]
Good call on the defaults. I think the simplification makes sense.
