### ISSUE TITLE
How about a CHANGELOG?

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [vkatsuba/rebar3_plugin#5]
It's always good to have one in any software project, IMO.
I usually go for something like

```
# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/).
```

**Comment by elbrujohalcon** [comment]
Github provides a brand new way to manage this in the release notes... The ones for 0.1.0 were autogenerated with this method.

**Comment by vkatsuba** [comment]
Yes GitHub provided functionality for release notes generation, however I'm not sure if eg current repo will be migrated in other place - does GitHub release notes also migrated? Maybe make sense add the same in change log file what generated by GitHub for backup and extend bootstrap for remove it or create new empty change log file for new plugins. @elbrujohalcon what do you think about it?

**Comment by paulo-ferraz-oliveira** [comment]
I was thinking about the rare case of a private plugin too, for example (or those cases where you template from GitHub but then only use Hex for publishing). But I'm not strongly opinionated on this subject. The discussion though, might be fruitful.
