### ISSUE TITLE
How about a default elvis.config?

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [vkatsuba/rebar3_plugin#6]
I usually go with something like

```
[{elvis, [
    {config, [
        #{ dirs => ["src/**"],
           filter => "*.erl",
           ruleset => erl_files },
        #{ dirs => ["test/**"],
           filter => "*.erl",
           ruleset => erl_files },
        #{ dirs => ["."],
           filter => "rebar.config",
           ruleset => rebar_config },
        #{ dirs => ["."],
           filter => "elvis.config",
           ruleset => elvis_config }
    ]},
    {verbose, false}
]}].
```
to start.

`rebar3_lint` implements its own default, but it's a more reduced version of the above. Also, some people do prefer to not include `tests` in their analysis, but this is a template that can be stripped somewhat, right?

**Comment by vkatsuba** [comment]
Yes this template is stripped a little bit for now. We try to collect all information about - what will be useful and add it if this is will be helpful. Not sure if a lot of plugins is use elvis but as minimum we can try add it for default and remove it for new clean option for bootstrap when it will be implemented. @elbrujohalcon any opinions?

**Comment by elbrujohalcon** [comment]
I agree with you, @vkatsuba
