### ISSUE TITLE
rebar2 in .gitignore: why?

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [vkatsuba/rebar3_plugin#7]
If this is a rebar3 plugin for rebar3 plugins, why ignore stuff that's not generated by the plugin instance?

Also, to start, I think `.gitignore` can be as easy as

```
.rebar3
_build
erl_crash.dump
log
rebar3.crashdump
```

I'm also not fond of ignoring `_checkouts/`. If it's there, it's changing behaviour, so whatever gets pushed might be different from what is excepted. (and again, `_checkouts` isn't generated, but put there on purpose)

**Comment by elbrujohalcon** [comment]
Well... I use _checkouts for testing purposes, generally creating simlinks there. I don't want that pushed to the repo, thus... .git ignore ;)

**Comment by vkatsuba** [comment]
Yep... the gitignore was generated by default by GitHub and should be updated. Thanks.

**Comment by paulo-ferraz-oliveira** [comment]
> I use _checkouts for testing purposes, generally creating simlinks there.

Many of us do 😄 

> I don't want that pushed to the repo, thus... .git ignore ;)

I don't want it in the repo. either, but having something ignored locally (that you know causes different behaviour if not pushed) is many times undesirable.

My suggestion was in the sense of: I've created more confusion having it in `.gitignore` and not understanding why something remote wasn't working, then the other way around (ie. not hiding something I know is influencing behaviour).

**Comment by elbrujohalcon** [comment]
Got it. My experience (as a heavy user of `git commit -a`) is that I end up pushing the damn folder in every PR/commit only to revert that in the next one. 🤦

**Comment by paulo-ferraz-oliveira** [comment]
> as a heavy user of git commit -a

No time to waste 🏎️
