### ISSUE TITLE
registered+modules in .app.src

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [vkatsuba/rebar3_plugin#8]
Not really sure having that there makes a difference.

**Comment by vkatsuba** [comment]
The main point was to keep the same base template what is provided by rebar3 and expand it. But maybe make sense update it as described above.

**Comment by paulo-ferraz-oliveira** [comment]
Yeah, but in the case of `rebar3` templates, you're creating an application (usually bundled with a release) for which those elements might make sense. I wonder if it's the same for `rebar3` plugins, though. Mind you my experience with coding these is somewhat limited. @elbrujohalcon, care to comment on the presence of those elements?
